### ISSUE TITLE
Eternal-jukebox: An error occured

### ISSUE THREAD

**Issue by TheGeeKing** [Pithaya/spicetify-apps-dist#32]
When I click on the app icon on the left bar I get the an error occured page with the refresh button.
Also it seems like it should add a button at the bottom bar which isn't there for me, but it adds a fullscreen one:
![image](https://github.com/Pithaya/spicetify-apps-dist/assets/58857539/c9e36ee5-aa8a-4da7-ac0a-3737a52feaba)

Traceback when I click on the app icon from `window.jukebox.isEnabled ? null !== e ? r.default.createElement("div", {`:
```
TypeError: Cannot read properties of undefined (reading 'isEnabled')
    at Ye (spicetify-routes-eternal-jukebox.js:10:6997)
    at aa (vendor~xpui.js:29:2035383)
    at Js (vendor~xpui.js:29:2087508)
    at Lc (vendor~xpui.js:29:2074786)
    at Nc (vendor~xpui.js:29:2074714)
    at Cc (vendor~xpui.js:29:2074577)
    at yc (vendor~xpui.js:29:2071564)
    at vendor~xpui.js:29:2021302
    at t.unstable_runWithPriority (vendor~xpui.js:29:2289972)
    at Ko (vendor~xpui.js:29:2021079)
```

Sometimes homepage and others can have the an error occured in this case from `o.forwardRef)(({color: t="currentColor", size: e=24, strokeWidth: r=2, children: n, ...i},s)=>(0,`:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'forwardRef')
    at extension.js:1:9107
    at extension.js:1:44420
(
```

**Comment by Tr3yWay996** [comment]
Me its not even letting me go on the tab, th

**Comment by Pithaya** [comment]
It's fixed, thanks for the error details!

**Comment by TheGeeKing** [comment]
You're welcome. It's now working you can close #34 too.
